sqlite:
  db: jdbc:sqlite:resources/db/files-counter.db
  timeout: 30 # Sql statement timeout execution (sec.)

rest-server:
  port: 8080

log4j:
  properties: resources/log4j.properties

index-search:
  query:
    default-field: 'content'
    max-count-result: 100

tika:
  limit: -1 # Unlimited chars count

storage:
  files: /files-storage/files
  indexes: /files-storage/indexes
  buffer:
    files: /files-storage/buffer/files
    indexes: /files-storage/buffer/indexes

processing-queue:
  name: queue:buffer
  timeout: 0
  address: localhost