sqlite-db: jdbc:sqlite:resources/db/files-counter.db

rest-server:
  port: 8080

log4j:
  properties: resources/log4j.properties

storage:
  files: /files-storage/files
  indexes: /files-storage/indexes
  buffer:
    files: /files-storage/buffer/files
    indexes: /files-storage/buffer/indexes

processing-queue:
  name: queue:buffer
  timeout: 0
  address: localhost

document-attributes:
  default:
    - id
    - path
    - owner
    - category
  dispatchers:
  safety:
  control: